name: 3-Tier-Full-Stack
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run Unit Tests
        run: | 
          npm install
          npm test 

  build:
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Project
        run: |
          npm run build
          tar -czvf next.tar.gz build/

  deploy:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "About to Deploy"
            cd /path/to/your/project
            git pull
            npm start
